name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  debug:
    permissions:
      actions: read
      id-token: write
      contents: read
    uses: bdehamer/workflows/.github/workflows/oidc-dump.yml@main
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
